camera:
  ae_enabled: false
  analog_gain: 4
  contrast: 116
  exposure_us: 5187
  gamma: 90
  reverse_x: false
  reverse_y: false
detection:
  backbone: resnet18
  n_augmentations: 100
  threshold: 90.0
